version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  deploy-prod:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      -- run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./deploy_project.sh”

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy-prod
          filters:
            branches:
              only:
                - master
          requires:
            -build-and-test