version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:8
    working_directory: /tmp

jobs:
  build:
    executor: my-executor
    working_directory: ~/r
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: "~"
          paths:
            - r/_site

  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ./_site
      # - run: mkdir ~/.ssh
      # - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run: sudo apt install rsync
      - run:
          name: Deploy Over SSH
          command: |
            rsync -avz -e "ssh" --progress * $DROPLET_USER@$DROPLET_IP:/var/www/100days.briiquach.com/html
#            scp -r build/* $SSH_USER@$SSH_HOST:build
      # - run: ssh $SSH_USER@$SSH_HOST 'chmod -R 755 ~/build'

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
